### ISSUE TITLE
Error Installation

### ISSUE THREAD

**Issue by odyright** [ah-jr/TAcrylicForm#1]
It said:
[dcc32 Fatal Error] AcrylicGhostPanelU.pas(19): F2613 Unit 'GR32' not found.
when i tried to install.

**Comment by ah-jr** [comment]
I'll make a commit to remove this dependency and make the installation process easier, but for the time being: 

- Pull the latest commit in which I added the GR32 files, build and install.
- In the project that you're going to use the components, go Project->Options->Building->Delphi Compiler->Search Path and add both folders "TAcrylicForm\deps\GR32" and "TAcrylicForm\src" 
- To make your form acrylic, add **AcrylicFormU** to the uses list and substitute **class(TForm)** with **class(TAcrylicForm)**, like that:

```
unit Unit1;

interface

uses
  Winapi.Windows,
  Winapi.Messages,
  System.SysUtils,
  System.Variants,
  System.Classes,
  Vcl.Graphics,
  Vcl.Controls,
  Vcl.Forms,
  Vcl.Dialogs,
  AcrylicFormU;

type
  TForm1 = class(TAcrylicForm)
  private
    { Private declarations }
  public
    { Public declarations }
  end;
```

**Comment by ah-jr** [comment]
Updated the project now, should work fine without the additional steps.
Don't forget to run Delphi as admin when installing.

**Comment by odyright** [comment]
Thank you for your assistance! It seems it's only available for Vcl.

**Comment by ah-jr** [comment]
Yes, you can try this if you're using FireMonkey:
https://github.com/ah-jr/FMX-form-with-blurred-background

it's much simpler though
